
font=JetBrainsMono Nerd Font:size=16
# font=Cascadia Code NF:size=18
font-size-adjustment=0.5

[main]
include = ~/.config/foot/themes/monokai.ini

[mouse]
hide-when-typing = yes
alternate-scroll-mode=yes

[mouse-bindings]
primary-paste = BTN_MIDDLE

[cursor]
style = underline #underline #block #beam
blink = yes
blink-rate = 1000
underline-thickness = 2

[url]
launch = xdg-open ${url}
label-letters = sadfjklewcmpgh
style = dashed
osc8-underline = url-mode
regex = (((https?://|mailto:|ftp://|file:|ssh:|ssh://|git://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)|www\.)([0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]+|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*')+([0-9a-zA-Z/#@$&*+=~_%^\-]|\([]\["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\)|\[[\(\)"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*\]|"[]\[\(\)0-9a-zA-Z:/?#@!$&'*+,;=.~_%^\-]*"|'[]\[\(\)0-9a-zA-Z:/?#@!$&*+,;=.~_%^\-]*'))

[environment]
TERMINAL = foot
BROWSER = brave

[desktop-notifications]
command = notify-send --wait --app-name ${app-id} --icon ${app-id} --category ${category} --urgency ${urgency} --expire-time ${expire-time} --hint STRING:image-path:${icon} --hint BOOLEAN:suppress-sound:${muted} --hint STRING:sound-name:${sound-name} --replace-id ${replace-id} ${action-argument} --print-id -- ${title} ${body}
command-action-argument=--action ${action-name}=${action-label}  # opsional
inhibit-when-focused=yes  # biar gak ganggu saat pakai terminal

[scrollback]
multiplier = 4.0
indicator-format = percentage
# indicator-format= 󱘎

[key-bindings]
quit = none
pipe-scrollback = [wl-copy] Control+Shift+a
pipe-command-output = [wl-copy] Control+Shift+g

# vim:ft=dosini
