
general {
    lock_cmd = pidof hyprlock || hyprlock --grace 10
    ignore_systemd_inhibit = false
    ignore_dbus_inhibit = false
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 200
    on-timeout = brightnessctl -s set 5
    on-resume = brightnessctl -r
}

listener {
    timeout = 350
    on-timeout = loginctl lock-session
}

listener {
    timeout = 420
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

listener {
    timeout = 660
    on-timeout = systemctl suspend
}
