typeset -U opts
opts=(
    AUTOCD
    AUTO_MENU
    AUTO_PARAM_SLASH
    COMPLETE_IN_WORD
    COMPLETE_ALIASES
    NO_MENU_COMPLETE
    HASH_LIST_ALL
    ALWAYS_TO_END
    NOTIFY
    NOHUP
    MAILWARN
    INTERACTIVE_COMMENTS
    NOBEEP
    APPEND_HISTORY
    SHARE_HISTORY
    INC_APPEND_HISTORY
    EXTENDED_HISTORY
    HIST_SAVE_BY_COPY
    HIST_IGNORE_ALL_DUPS
    HIST_IGNORE_SPACE
    HIST_NO_FUNCTIONS
    HIST_EXPIRE_DUPS_FIRST
    HIST_SAVE_NO_DUPS
    HIST_REDUCE_BLANKS
)

for opt in "${opts[@]}";do
    setopt $opt
done

while read -r opt; do
    unsetopt $opt
done <<-EOF
AUTO_CD
AUTO_PUSHD
EXTENDED_GLOB
GLOB_STAR_SHORT
GLOB_DOTS
EOF
